server:
  port: 7000

spring:
  application:
    name: hystrix_start


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 


management:
  endpoints:
    web:
      exposure:
        include: '*'
         
